project:
  type: website
  output-dir: docs

website:
  title: "Elke Windschitl"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog-settings.qmd
        text: Blog Posts

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

