project:
  type: website
  output-dir: docs

website:
  title: "Elke Windschitl"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - mystyles.scss
    mainfont: Noto Serif Gujarati
    #css: styles.css
    toc: true

editor: visual

